project_id = "bhkqdxhyceflfesxrztm"

[functions.ai-trainer]
verify_jwt = true

[functions.search-vet-clinics]
verify_jwt = true

[functions.upsert-vet-clinic]
verify_jwt = true

[functions.admin-seed-vet-clinics]
verify_jwt = true